#!/usr/bin/env python3
"""Generate the Research Dashboard (research/dashboard.md).

Reads the research store (/tmp/research-study by default) and the
laboratory markdown documents, and emits a metrics snapshot of the
laboratory's scientific state. Deterministic given the store state.

Usage:
    python3 research/generate_dashboard.py [--root /tmp/research-study]
"""

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RESEARCH_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(REPO_ROOT / "research_platform"))

from research_platform.store import ResearchStore  # noqa: E402


def count_pattern(path: Path, pattern: str) -> int:
    if not path.is_file():
        return 0
    return len(re.findall(pattern, path.read_text(encoding="utf-8"), re.M))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="/tmp/research-study")
    args = ap.parse_args()

    store = ResearchStore(args.root)

    # --- Store statistics ---
    experiments = store.find_experiments()
    n_exp = len(experiments)
    n_exp_completed = sum(1 for e in experiments if e.status == "completed")
    n_exp_failed = sum(1 for e in experiments if e.status == "failed")
    n_runs = 0
    n_runs_completed = 0
    reproductions = []
    for e in experiments:
        runs = store.get_runs(e.uuid)
        n_runs += len(runs)
        n_runs_completed += sum(1 for r in runs if r.status == "completed")
        reproductions.extend(store.get_reproductions(e.uuid))
    n_repro = len(reproductions)
    n_repro_matched = sum(1 for r in reproductions if r.status == "matched")
    n_repro_unverifiable = sum(1 for r in reproductions if r.status == "unverifiable")
    n_repro_mismatched = n_repro - n_repro_matched - n_repro_unverifiable
    n_datasets = len(store.list_datasets())

    # --- Benchmark wins: strategy cells vs buy & hold on the same basis ---
    buyhold = None
    for e in experiments:
        if e.module == "buy_hold":
            run = store.get_latest_run(e.uuid)
            if run is not None:
                buyhold = run.metrics.get("ann_sharpe")
            break
    n_cells = 0
    n_beat_buyhold = 0
    best_cell_sharpe = None
    seen_cells = set()
    if buyhold is not None:
        for e in experiments:
            p = e.params
            if (e.module == "gap_strategy" and e.seed == 0
                    and float(p.get("cost_bps", -1)) == 0.0):
                key = (float(p["threshold_pct"]), int(p["hold_days"]),
                       str(p["direction"]))
                if key in seen_cells:
                    continue
                seen_cells.add(key)
                run = store.get_latest_run(e.uuid)
                if run is None or "ann_sharpe" not in run.metrics:
                    continue
                sharpe = float(run.metrics["ann_sharpe"])
                n_cells += 1
                if sharpe >= buyhold:
                    n_beat_buyhold += 1
                best_cell_sharpe = max(best_cell_sharpe or sharpe, sharpe)

    # --- Laboratory document statistics ---
    catalog_h = count_pattern(RESEARCH_DIR / "catalog.md", r"^### H-")
    edge_entries = count_pattern(RESEARCH_DIR / "edge_database.md", r"^### E-\d+")
    edge_accepted = count_pattern(RESEARCH_DIR / "edge_database.md",
                                  r"^- \*\*verdict:\*\* `accepted`")
    edge_rejected = count_pattern(RESEARCH_DIR / "edge_database.md",
                                  r"^- \*\*verdict:\*\* `rejected`")
    nk_entries = count_pattern(RESEARCH_DIR / "negative_knowledge.md", r"^## NK-\d+")
    assets = count_pattern(RESEARCH_DIR / "asset_registry.md", r"^\| AS-")
    features_doc = count_pattern(RESEARCH_DIR / "feature_registry.md", r"^### F-")
    roadmap_campaigns = count_pattern(RESEARCH_DIR / "roadmap.md", r"^## C\d{3}")
    raw_csvs = len(list((REPO_ROOT / "data").glob("*.csv")))
    hypotheses_tested = edge_accepted + edge_rejected

    # --- Commit snapshot ---
    commit = "unknown"
    try:
        import subprocess
        commit = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:  # noqa: BLE001
        pass

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    repro_rate = (n_repro_matched / n_repro) if n_repro else 0.0

    def row(label, value):
        return "| %s | %s |" % (label, value)

    lines = [
        "# Research Dashboard — Automated Laboratory Summary",
        "",
        "_Auto-generated by `research/generate_dashboard.py`; do not edit by "
        "hand. Snapshot: %s — repo commit: `%s` — store: `%s`._"
        % (now, commit, args.root),
        "",
        "## 1. Campaigns and hypotheses",
        "",
        "| Metric | Value |",
        "|---|---|",
        row("Campaigns completed", "1 (C001 gap continuation — REJECTED)"),
        row("Campaigns active", "0"),
        row("Campaigns planned (roadmap)", roadmap_campaigns),
        row("Hypotheses catalogued", catalog_h),
        row("Hypotheses tested", hypotheses_tested),
        row("Hypotheses accepted", edge_accepted),
        row("Hypotheses rejected", edge_rejected),
        row("Negative knowledge entries", nk_entries),
        "",
        "## 2. Experiments",
        "",
        "| Metric | Value |",
        "|---|---|",
        row("Experiments registered", n_exp),
        row("Experiments completed", n_exp_completed),
        row("Experiments failed", n_exp_failed),
        row("Runs recorded", n_runs),
        row("Runs completed", n_runs_completed),
        "",
        "## 3. Reproducibility",
        "",
        "| Metric | Value |",
        "|---|---|",
        row("Reproduction attempts", n_repro),
        row("Matched (exact metrics)", n_repro_matched),
        row("Unverifiable (setup/dirty-tree)", n_repro_unverifiable),
        row("Mismatched", n_repro_mismatched),
        row("Verified reproducibility rate", "%.1f%%" % (100.0 * repro_rate)),
        "",
        "## 4. Benchmarks and edges",
        "",
        "| Metric | Value |",
        "|---|---|",
        row("Buy & hold Sharpe (ES daily, C001 window)",
            "%.2f" % buyhold if buyhold is not None else "n/a"),
        row("Strategy cells searched (cost 0)", n_cells),
        row("Cells beating buy & hold", n_beat_buyhold),
        row("Best strategy cell Sharpe", "%.2f" % best_cell_sharpe
            if best_cell_sharpe is not None else "n/a"),
        row("Accumulated edges (accepted)", edge_accepted),
        row("Accumulated negative results", nk_entries),
        "",
        "## 5. Assets",
        "",
        "| Metric | Value |",
        "|---|---|",
        row("Registered datasets", n_datasets),
        row("Raw data files in repo (incl. unregistered)", raw_csvs),
        row("Reusable assets (asset registry)", assets),
        row("Implemented features documented", features_doc),
        "",
        "## 6. Headline knowledge",
        "",
        "- **E-0001:** Gap continuation on ES daily is REJECTED (DSR p=0.285, "
        "White's RC p≈0.39).",
        "- **E-0002:** On ES daily 2016-2026 the benchmark ladder is: "
        "EMA(10,100) 0.89 > SMA(10,100) 0.86 > buy & hold 0.79 > best gap "
        "cell 0.52.",
        "- **E-0003:** Measured false-discovery calibration: 14% of 36 "
        "searched cells nominally significant at 5% — single-test gates are "
        "insufficient for grids.",
        "- **NK-0001:** Gap continuation may only be reinvestigated under the "
        "documented triggers (intraday fills, volume conditioning, new "
        "markets, or the opposite-sign rule C002).",
        "",
        "## 7. Read next",
        "",
        "- Roadmap: `research/roadmap.md` (next campaign: C002 gap fading).",
        "- Meta-learning: `research/meta_learning.md`.",
        "- Registry of record for components: `research/asset_registry.md`.",
        "",
    ]
    out = RESEARCH_DIR / "dashboard.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print("wrote %s" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
